// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDra1TuafZKgns1uzVMgeoPnWsf_UF0GSM',
    appId: '1:433047565987:web:d9b0fd4ab228a7708f3116',
    messagingSenderId: '433047565987',
    projectId: 'appshoppe-260329',
    authDomain: 'appshoppe-260329.firebaseapp.com',
    storageBucket: 'appshoppe-260329.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA8spd35nSMyVALPFsulo1nCXimeVkLCU',
    appId: '1:433047565987:android:2d605db9b64e343c8f3116',
    messagingSenderId: '433047565987',
    projectId: 'appshoppe-260329',
    storageBucket: 'appshoppe-260329.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvnsLU3XTkKqt6XtAe2t_ZCTGDf5RVPrQ',
    appId: '1:433047565987:ios:613ea06a8475d3848f3116',
    messagingSenderId: '433047565987',
    projectId: 'appshoppe-260329',
    storageBucket: 'appshoppe-260329.firebasestorage.app',
    iosBundleId: 'com.example.appshoppe',
  );
}
